robot:
  kinematics: 'omni'
  length: 1.6
  width: 2.0
  max_speed: [8.0, 8.0, 3.14]
  max_acce:  [8.0, 8.0, 3.14]


train:
  direct_train: true
  data_size: 100000
  data_range: [-25, -25, 25, 25]
  batch_size: 2048
  epoch: 5000
  valid_freq: 250
  save_freq: 500
  lr: 5e-5
  lr_decay: 0.5
  decay_freq: 1500
  # CPU Training Optimization Parameters (based on PyTorch best practices)
  data_gen_workers: 8  # Number of parallel workers for data generation (0 = sequential)
  dataloader_num_workers: 4  # Number of DataLoader workers (0 = single process, recommended: 2-4 for CPU)
  persistent_workers: true  # Keep workers alive between epochs (reduces overhead, requires num_workers > 0)
  prefetch_factor: 2  # Number of batches to prefetch per worker (default: 2)




